#ifndef _ALTERA_PIXEL_DMA_ADDR_TRANSLATION_H_
#define _ALTERA_PIXEL_DMA_ADDR_TRANSLATION_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'Computer_System' in
 * file 'Computer_System.sopcinfo'.
 */

/*
 * This file contains macros for module 'Pixel_DMA_Addr_Translation' and devices
 * connected to the following master:
 *   master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'VGA_Subsystem_VGA_Pixel_DMA', class 'altera_up_avalon_video_pixel_buffer_dma'
 * The macros are prefixed with 'VGA_SUBSYSTEM_VGA_PIXEL_DMA_'.
 * The prefix is the slave descriptor.
 */
#define VGA_SUBSYSTEM_VGA_PIXEL_DMA_COMPONENT_TYPE altera_up_avalon_video_pixel_buffer_dma
#define VGA_SUBSYSTEM_VGA_PIXEL_DMA_COMPONENT_NAME VGA_Subsystem_VGA_Pixel_DMA
#define VGA_SUBSYSTEM_VGA_PIXEL_DMA_BASE 0x0
#define VGA_SUBSYSTEM_VGA_PIXEL_DMA_SPAN 16
#define VGA_SUBSYSTEM_VGA_PIXEL_DMA_END 0xf


#endif /* _ALTERA_PIXEL_DMA_ADDR_TRANSLATION_H_ */
